# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sys_Button',
            fields=[
                ('KeyId', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('FullName', models.CharField(max_length=30, verbose_name='名称')),
                ('Icon', models.CharField(max_length=30, verbose_name='图标')),
                ('ButtonEvent', models.CharField(max_length=30, verbose_name='按钮点击事件名称')),
                ('Description', models.CharField(max_length=30, verbose_name='描述')),
                ('SortNum', models.IntegerField(verbose_name='排序')),
                ('IsDeleted', models.BooleanField(verbose_name='是否删除')),
                ('DateTime', models.DateTimeField(verbose_name='时间')),
            ],
        ),
    ]
