# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_button',
            name='FullName',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
    ]
