# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sys_dictionary_sys_errorlog_sys_menu_sys_menubutton_sys_organization_sys_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sys_RoleMenu',
            fields=[
                ('KeyId', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('RoleId', models.CharField(max_length=50, verbose_name='角色ID')),
                ('MenuId', models.CharField(max_length=50, verbose_name='菜单ID')),
                ('DateTime', models.DateTimeField(verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='Sys_RoleMenuButton',
            fields=[
                ('KeyId', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('RoleId', models.CharField(max_length=50, verbose_name='角色ID')),
                ('MenuId', models.CharField(max_length=50, verbose_name='菜单ID')),
                ('ButtonId', models.CharField(max_length=50, verbose_name='按钮ID')),
                ('DateTime', models.DateTimeField(verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='Sys_User',
            fields=[
                ('KeyId', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('Account', models.CharField(max_length=50, verbose_name='账号')),
                ('PassWord', models.CharField(max_length=50, verbose_name='密码')),
                ('FullName', models.CharField(max_length=50, verbose_name='称呼')),
                ('Job', models.CharField(max_length=50, verbose_name='职位')),
                ('Educational', models.CharField(max_length=50, verbose_name='学历')),
                ('FinishSchool', models.CharField(max_length=50, verbose_name='毕业学校')),
                ('OrgId', models.CharField(max_length=50, verbose_name='所属组织')),
                ('HeadImg', models.CharField(max_length=50, verbose_name='头像')),
                ('Phone', models.CharField(max_length=50, verbose_name='联系方式')),
                ('Email', models.CharField(max_length=50, verbose_name='邮件')),
                ('Sex', models.BooleanField(verbose_name='性别')),
                ('BirthDay', models.DateTimeField(verbose_name='出生日期')),
                ('IDCard', models.CharField(max_length=50, verbose_name='身份证')),
                ('Address', models.CharField(max_length=50, verbose_name='地址')),
                ('Description', models.CharField(max_length=250, verbose_name='简介')),
                ('SortNum', models.IntegerField(verbose_name='排序')),
                ('IsDeleted', models.BooleanField(verbose_name='是否删除')),
                ('DateTime', models.DateTimeField(verbose_name='时间')),
            ],
        ),
    ]
