# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_sys_rolemenu_sys_rolemenubutton_sys_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sys_UserRole',
            fields=[
                ('KeyId', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('RoleId', models.CharField(max_length=50, verbose_name='角色ID')),
                ('UserId', models.CharField(max_length=50, verbose_name='用户ID')),
                ('DateTime', models.DateTimeField(verbose_name='时间')),
            ],
        ),
    ]
