# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sys_userrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sys_button',
            options={'verbose_name': '权限按钮', 'verbose_name_plural': '权限按钮'},
        ),
        migrations.AlterModelOptions(
            name='sys_dictionary',
            options={'verbose_name': '字典', 'verbose_name_plural': '字典列表'},
        ),
        migrations.AlterModelOptions(
            name='sys_errorlog',
            options={'verbose_name': '日志', 'verbose_name_plural': '日志记录'},
        ),
        migrations.AlterModelOptions(
            name='sys_menu',
            options={'verbose_name': '菜单', 'verbose_name_plural': '菜单列表'},
        ),
        migrations.AlterModelOptions(
            name='sys_menubutton',
            options={'verbose_name': '菜单按钮', 'verbose_name_plural': '菜单按钮列表'},
        ),
        migrations.AlterModelOptions(
            name='sys_organization',
            options={'verbose_name': '组织架构', 'verbose_name_plural': '组织架构列表'},
        ),
        migrations.AlterModelOptions(
            name='sys_role',
            options={'verbose_name': '角色', 'verbose_name_plural': '角色列表'},
        ),
        migrations.AlterModelOptions(
            name='sys_rolemenu',
            options={'verbose_name': '角色对应菜单', 'verbose_name_plural': '角色对应菜单列表'},
        ),
        migrations.AlterModelOptions(
            name='sys_rolemenubutton',
            options={'verbose_name': '角色对应菜单按钮', 'verbose_name_plural': '角色对应菜单按钮列表'},
        ),
        migrations.AlterModelOptions(
            name='sys_user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户列表'},
        ),
        migrations.AlterModelOptions(
            name='sys_userrole',
            options={'verbose_name': '用户角色', 'verbose_name_plural': '用户角色列表'},
        ),
        migrations.AlterField(
            model_name='sys_button',
            name='Description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='sys_dictionary',
            name='Description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='sys_menu',
            name='Description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='sys_organization',
            name='Description',
            field=models.TextField(verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='sys_role',
            name='Description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='Address',
            field=models.CharField(max_length=150, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='Description',
            field=models.TextField(verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='Educational',
            field=models.CharField(max_length=100, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='FinishSchool',
            field=models.CharField(max_length=100, verbose_name='毕业学校'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='HeadImg',
            field=models.CharField(max_length=250, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='PassWord',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
    ]
