# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171214_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_dictionary',
            name='ParentId',
            field=models.IntegerField(verbose_name='父级'),
        ),
        migrations.AlterField(
            model_name='sys_menu',
            name='ParentId',
            field=models.IntegerField(verbose_name='父级'),
        ),
        migrations.AlterField(
            model_name='sys_menubutton',
            name='ButtonId',
            field=models.IntegerField(verbose_name='按钮ID'),
        ),
        migrations.AlterField(
            model_name='sys_menubutton',
            name='MenuId',
            field=models.IntegerField(verbose_name='菜单ID'),
        ),
        migrations.AlterField(
            model_name='sys_organization',
            name='ParentId',
            field=models.IntegerField(verbose_name='父级ID'),
        ),
        migrations.AlterField(
            model_name='sys_rolemenu',
            name='MenuId',
            field=models.IntegerField(verbose_name='菜单ID'),
        ),
        migrations.AlterField(
            model_name='sys_rolemenu',
            name='RoleId',
            field=models.IntegerField(verbose_name='角色ID'),
        ),
        migrations.AlterField(
            model_name='sys_rolemenubutton',
            name='ButtonId',
            field=models.IntegerField(verbose_name='按钮ID'),
        ),
        migrations.AlterField(
            model_name='sys_rolemenubutton',
            name='MenuId',
            field=models.IntegerField(verbose_name='菜单ID'),
        ),
        migrations.AlterField(
            model_name='sys_rolemenubutton',
            name='RoleId',
            field=models.IntegerField(verbose_name='角色ID'),
        ),
        migrations.AlterField(
            model_name='sys_userrole',
            name='RoleId',
            field=models.IntegerField(verbose_name='角色ID'),
        ),
        migrations.AlterField(
            model_name='sys_userrole',
            name='UserId',
            field=models.IntegerField(verbose_name='用户ID'),
        ),
    ]
